export const dataMock = [
  {
    adult: false,
    backdrop_path: '/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg',
    genre_ids: [10751, 35, 12, 14],
    id: 950387,
    original_language: 'en',
    original_title: 'A Minecraft Movie',
    overview:
      "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
    popularity: 990.9442,
    poster_path: '/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg',
    release_date: '2025-03-31',
    title: 'A Minecraft Movie',
    video: false,
    vote_average: 6.1,
    vote_count: 354,
  },
  {
    adult: false,
    backdrop_path: '/is9bmV6uYXu7LjZGJczxrjJDlv8.jpg',
    genre_ids: [28, 12],
    id: 1229730,
    original_language: 'fr',
    original_title: 'Carjackers',
    overview:
      "By day, they're invisible—valets, hostesses, and bartenders at a luxury hotel. By night, they're the Carjackers, a crew of skilled drivers who track and rob wealthy clients on the road. As they plan their ultimate heist, the hotel director hires a ruthless hitman, to stop them at all costs. With danger closing in, can Nora, Zoe, Steve, and Prestance pull off their biggest score yet?",
    popularity: 297.0009,
    poster_path: '/wbkPMTz2vVai7Ujyp0ag7AM9SrO.jpg',
    release_date: '2025-03-27',
    title: 'Carjackers',
    video: false,
    vote_average: 6.2,
    vote_count: 95,
  },
  {
    adult: false,
    backdrop_path: '/ce3prrjh9ZehEl5JinNqr4jIeaB.jpg',
    genre_ids: [28, 53, 878],
    id: 822119,
    original_language: 'en',
    original_title: 'Captain America: Brave New World',
    overview:
      'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
    popularity: 283.1613,
    poster_path: '/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
    release_date: '2025-02-12',
    title: 'Captain America: Brave New World',
    video: false,
    vote_average: 6.098,
    vote_count: 1251,
  },
  {
    adult: false,
    backdrop_path: '/gsQJOfeW45KLiQeEIsom94QPQwb.jpg',
    genre_ids: [28, 53],
    id: 1125899,
    original_language: 'en',
    original_title: 'Cleaner',
    overview:
      "When a group of radical activists take over an energy company's annual gala, seizing 300 hostages, an ex-soldier turned window cleaner suspended 50 storeys up on the outside of the building must save those trapped inside, including her younger brother.",
    popularity: 263.1996,
    poster_path: '/mwzDApMZAGeYCEVjhegKvCzDX0W.jpg',
    release_date: '2025-02-19',
    title: 'Cleaner',
    video: false,
    vote_average: 6.511,
    vote_count: 180,
  },
  {
    adult: false,
    backdrop_path: '/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg',
    genre_ids: [14, 12, 28],
    id: 324544,
    original_language: 'en',
    original_title: 'In the Lost Lands',
    overview:
      'A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.',
    popularity: 534.2664,
    poster_path: '/iHf6bXPghWB6gT8kFkL1zo00x6X.jpg',
    release_date: '2025-02-27',
    title: 'In the Lost Lands',
    video: false,
    vote_average: 6.14,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/xBrx6O1RIhjtWmVthZIANuQz7Z2.jpg',
    genre_ids: [28, 80, 53],
    id: 1197306,
    original_language: 'en',
    original_title: 'A Working Man',
    overview:
      "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
    popularity: 215.8897,
    poster_path: '/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg',
    release_date: '2025-03-26',
    title: 'A Working Man',
    video: false,
    vote_average: 6.4,
    vote_count: 170,
  },
  {
    adult: false,
    backdrop_path: '/hGLywNhy1Fo1rNFHsNZsXGS69B8.jpg',
    genre_ids: [878, 35, 12],
    id: 696506,
    original_language: 'en',
    original_title: 'Mickey 17',
    overview:
      'Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.',
    popularity: 241.9858,
    poster_path: '/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg',
    release_date: '2025-02-28',
    title: 'Mickey 17',
    video: false,
    vote_average: 6.955,
    vote_count: 1334,
  },
  {
    adult: false,
    backdrop_path: '/sNx1A3822kEbqeUxvo5A08o4N7o.jpg',
    genre_ids: [28, 35, 53],
    id: 1195506,
    original_language: 'en',
    original_title: 'Novocaine',
    overview:
      'When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.',
    popularity: 235.1646,
    poster_path: '/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg',
    release_date: '2025-03-12',
    title: 'Novocaine',
    video: false,
    vote_average: 7,
    vote_count: 220,
  },
  {
    adult: false,
    backdrop_path: '/AlpDRp3Qaf2JvlQDzXS8kiYxTf8.jpg',
    genre_ids: [28, 53],
    id: 1212855,
    original_language: 'en',
    original_title: 'Fight or Flight',
    overview:
      "A mercenary takes on the job of tracking down a target on a plane but must protect her when they're surrounded by people trying to kill both of them.",
    popularity: 197.3977,
    poster_path: '/x4nWnfgJvL045rcUCSJzfgIIY9i.jpg',
    release_date: '2025-04-03',
    title: 'Fight or Flight',
    video: false,
    vote_average: 4.63,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: '/ibF5XVxTzf1ayzZrmiJqgeQ39Qk.jpg',
    genre_ids: [28, 10752],
    id: 1373723,
    original_language: 'en',
    original_title: 'The Codes of War',
    overview:
      'War stories about family, ethics and honor include the true story of two U.S. Marines who in a span of six seconds, must stand their ground to stop a suicide truck bomb, a Navy Corpsman who attempts to hold on to his humanity, and a WW2 soldier who gets separated from his squad and is forced to re-evaluate his code.',
    popularity: 191.6448,
    poster_path: '/oXeiQAfRK90pxxhP5iKPXQqAIN1.jpg',
    release_date: '2025-03-20',
    title: 'The Codes of War',
    video: false,
    vote_average: 6.102,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: '/9OO6I25MHhCDd0XwNk4oZl0fpwB.jpg',
    genre_ids: [28, 18],
    id: 1261050,
    original_language: 'da',
    original_title: 'De lydløse',
    overview:
      'In 2008, a group of men from Denmark and across Europe pull off the biggest heist of all time on Danish soil. Kasper, a boxer with few chances left in life, is offered the opportunity to plan the robbery by its foreign initiators.',
    popularity: 174.6724,
    poster_path: '/7NLY1jNwtZX1yVzwVoBeAhaBE8i.jpg',
    release_date: '2024-10-31',
    title: 'The Quiet Ones',
    video: false,
    vote_average: 4.983,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/nhx0ttmAS2w8e6hyIcKoNvgHoix.jpg',
    genre_ids: [27, 53, 14],
    id: 1020414,
    original_language: 'en',
    original_title: "Peter Pan's Neverland Nightmare",
    overview:
      'Wendy Darling strikes out in an attempt to rescue her brother Michael from the clutches of the evil Peter Pan who intends to send him to Neverland. Along the way she meets a twisted Tinkerbell, who is hooked on what she thinks is fairy dust.',
    popularity: 156.8976,
    poster_path: '/mOR1Ks0EcXocwMV4EPv4letz0F5.jpg',
    release_date: '2025-01-13',
    title: "Peter Pan's Neverland Nightmare",
    video: false,
    vote_average: 5.104,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: '/jiKwojRdwMYsDEMxQp5NFS3sOKb.jpg',
    genre_ids: [27],
    id: 1282980,
    original_language: 'en',
    original_title: '825 Forest Road',
    overview:
      'After a family tragedy, Chuck Wilson hopes to start a new life in Ashland Falls with his wife Maria and little sister Elizabeth, but he quickly discovers that the town has a dark history of being haunted by a ghostly woman who drives residents to suicide.',
    popularity: 142.9193,
    poster_path: '/ohESp5Nw49OD4ExCeNYCEIGX2iq.jpg',
    release_date: '2025-04-04',
    title: '825 Forest Road',
    video: false,
    vote_average: 5.737,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: '/e807jDKiFcntZS32ze88X6I96OD.jpg',
    genre_ids: [16, 28],
    id: 1297763,
    original_language: 'ja',
    original_title: 'ニンジャバットマン対ヤクザリーグ',
    overview:
      'The Batman family has returned to the present to discover that Japan has disappeared, and a giant island - Hinomoto - is now in the sky over Gotham City.  At the top sit the Yakuza, a group of superpowered individuals who reign without honor or humanity and look suspiciously like the Justice League. Now, it’s up to Batman and his allies to save Gotham!',
    popularity: 120.0763,
    poster_path: '/sVVT6GYFErVv0Lcc9NvqCu0iOxO.jpg',
    release_date: '2025-03-17',
    title: 'Batman Ninja vs. Yakuza League',
    video: false,
    vote_average: 6.627,
    vote_count: 122,
  },
  {
    adult: false,
    backdrop_path: '/9ctmJLf3uUngYkwHbRttukm2n5l.jpg',
    genre_ids: [18, 9648, 53],
    id: 1233575,
    original_language: 'en',
    original_title: 'Black Bag',
    overview:
      'When intelligence agent Kathryn Woodhouse is suspected of betraying the nation, her husband – also a legendary agent – faces the ultimate test of whether to be loyal to his marriage, or his country.',
    popularity: 117.2334,
    poster_path: '/hHPovtU4b96LHcoeEwRkGHI5btw.jpg',
    release_date: '2025-03-12',
    title: 'Black Bag',
    video: false,
    vote_average: 6.384,
    vote_count: 302,
  },
  {
    adult: false,
    backdrop_path: '/xkjWiRQtrenqGRWO2Enry2JIl4d.jpg',
    genre_ids: [27],
    id: 1388366,
    original_language: 'pt',
    original_title: 'Popeye the Slayer Man',
    overview:
      'A curious group of friends sneak into an abandoned spinach canning factory to film a documentary on the legend of the "Sailor Man," who is said to haunt the factory and local docks.',
    popularity: 106.8782,
    poster_path: '/nVwu3mN7hr1yF467pGct3yQFM41.jpg',
    release_date: '2025-03-21',
    title: 'Popeye the Slayer Man',
    video: false,
    vote_average: 6.1,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: '/hwlyY7LJdEFbCPaGNXiskKKmJ5X.jpg',
    genre_ids: [28, 80, 53],
    id: 1126166,
    original_language: 'en',
    original_title: 'Flight Risk',
    overview:
      "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
    popularity: 112.0742,
    poster_path: '/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg',
    release_date: '2025-01-22',
    title: 'Flight Risk',
    video: false,
    vote_average: 6.104,
    vote_count: 603,
  },
  {
    adult: false,
    backdrop_path: '/xb9wpY31SeVZbfkevYuolhfV63w.jpg',
    genre_ids: [10751, 14],
    id: 447273,
    original_language: 'en',
    original_title: 'Snow White',
    overview:
      "Princess Snow White flees the castle when the Evil Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young thief named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom in the process.",
    popularity: 105.1103,
    poster_path: '/xWWg47tTfparvjK0WJNX4xL8lW2.jpg',
    release_date: '2025-03-19',
    title: 'Snow White',
    video: false,
    vote_average: 4.549,
    vote_count: 525,
  },
  {
    adult: false,
    backdrop_path: '/sulUXRukzh7WSK34y8mnaUcHo3y.jpg',
    genre_ids: [10749, 35, 18],
    id: 1254786,
    original_language: 'en',
    original_title: 'The Life List',
    overview:
      'When her mother sends her on a quest to complete a teenage bucket list, a young woman uncovers family secrets, finds romance — and rediscovers herself.',
    popularity: 103.3923,
    poster_path: '/5fg98cVo7da7OIK45csdLSd4NaU.jpg',
    release_date: '2025-03-27',
    title: 'The Life List',
    video: false,
    vote_average: 6.854,
    vote_count: 212,
  },
  {
    adult: false,
    backdrop_path: '/3kzw6Rw7TBujqtchJS2TSP3O2US.jpg',
    genre_ids: [27, 9648, 53],
    id: 1202479,
    original_language: 'en',
    original_title: 'Opus',
    overview:
      "A young writer is invited to the remote compound of a legendary pop star who mysteriously disappeared thirty years ago. Surrounded by the star's cult of sycophants and intoxicated journalists, she finds herself in the middle of his twisted plan.",
    popularity: 70.4611,
    poster_path: '/eAslhx6gKKD6c1vVY6YV9DSG5lb.jpg',
    release_date: '2025-03-13',
    title: 'Opus',
    video: false,
    vote_average: 5.336,
    vote_count: 58,
  },
];
